// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class CSVView
{
	//public class Row
	//{
		//public string using UnityEngine;;

	//}

	//List<Row> rowList = new List<Row>();
	//bool isLoaded = false;

	//public bool IsLoaded()
	//{
		//return isLoaded;
	//}

	//public List<Row> GetRowList()
	//{
	//	return rowList;
	//}

	//public void Load(TextAsset csv)
	//{
	//	rowList.Clear();
	//	string[][] grid = CsvParser2.Parse(csv.text);
	//	for(int i = 1 ; i < grid.Length ; i++)
	//	{
	//		Row row = new Row();
	//		row.using UnityEngine; = grid[i][0];

	//		rowList.Add(row);
	//	}
	//	isLoaded = true;
	//}

	//public int NumRows()
	//{
	//	return rowList.Count;
	//}

	//public Row GetAt(int i)
	//{
	//	if(rowList.Count <= i)
	//		return null;
	//	return rowList[i];
	//}

	//public Row Find_using UnityEngine;(string find)
	//{
	//	return rowList.Find(x => x.using UnityEngine; == find);
	//}
	//public List<Row> FindAll_using UnityEngine;(string find)
	//{
	//	return rowList.FindAll(x => x.using UnityEngine; == find);
	//}

}